spring.datasource.url=jdbc:postgresql://localhost:5432/uhyodb
spring.datasource.username=ssuzuki
spring.datasource.password=ss798888
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=app
spring.jpa.show-sql=true